### ISSUE TITLE
pysradb download not working 

### ISSUE THREAD

**Issue by fgypas** [saketkc/pysradb#14]
* pysradb version: 0.9.6
* Python version: 3.8.0
* Operating System: CentOS 7.5.1804

### Description

I tried to download an SRP project. 

### What I Did

```
pysradb download SRP083135
```

It returns the help message

When I try:
```
pysradb metadata SRP083135
```

I get a table with the study_accession, experiment_accession, sample_accession and run_accession.

**Comment by fgypas** [comment]
Hi @saketkc 

Thank you for the response.

I get the following error message:

>   File "miniconda3/envs/pysradb/bin/pysradb", line 10, in <module>
>     sys.exit(parse_args())
>   File "miniconda3/envs/pysradb/lib/python3.8/site-packages/pysradb/cli.py", line 1044, in parse_args
>     download(args.out_dir, args.db, args.srx, args.srp, args.skip_confirmation)
>   File "miniconda3/envs/pysradb/lib/python3.8/site-packages/pysradb/cli.py", line 139, in download
>     sradb.download(
>   File "miniconda3/envs/pysradb/lib/python3.8/site-packages/pysradb/sradb.py", line 1249, in download
>     srapaths = self._srapath_url(df.study_accession.unique()[0])
>   File "miniconda3/envs/pysradb/lib/python3.8/site-packages/pysradb/sradb.py", line 1174, in _srapath_url
>     raise Exception("Unable to run srapath.")
> Exception: Unable to run srapath.

Foivos

**Comment by saketkc** [comment]
Thanks @fgypas. I confirm this is a bug and is arising because of `pysradb` relying on `srapath` to get the new URLs. I will have a temporary fix soon. 

Thanks once again and sorry that `pysradb` is not completely useful for your use case at the moment.

**Comment by deepthi888** [comment]
Hi @saketkc,
could you please provide me some information on how to store the result which we get from 
"pysradb metadata SRP063732 --desc --expand" into pandas dataframe

Thanks in advance

**Comment by saketkc** [comment]
Hi @deepthi888, You can save the output to a tab separated file by doing:
```
pysradb metadata SRP063732 --desc --expand --saveto SRP063732.tsv
```

**Comment by deepthi888** [comment]
Hi @saketkc,
could you please provide me information on how to fetch the name of the organism by giving project id
I tried with this "pysradb metadata SRP063732 --desc --expand --detailed" but it fetched all the attributes information except name of the organism.

Thanks in advance

**Comment by saketkc** [comment]
@deepthi888 Can you please open a separate issue for your question? 
Thanks!

**Comment by saketkc** [comment]
Hi @fgypas,

I can confirm that [v0.9.9](https://github.com/saketkc/pysradb/releases/tag/v0.9.9) of pysradb fixes this.
Please let me know if you run into any issues and thanks a lot for your patience!
