### ISSUE TITLE
unpin `pandas`?

### ISSUE THREAD

**Issue by jbloom** [saketkc/pysradb#141]
Right now `pysradb` pins `pandas` to version 1.2.0, even though as far as I can tell this pinning isn't necessary for `pysradb`. Is it possible to just make the requirement `pandas>=1.2.0` so it's possible to use `pysradb` with newer versions of `pandas`?

**Comment by saketkc** [comment]
The hard pinning was specifically designed for the changes introduced in pandas 1.2.0 (the [nullable data support](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.2.0.html) that was not part of <1.2) so I agree, it is no longer necessary. I have unpinned all the requirements (and confirmed they don't break the tests).

I will make a release in the coming weeks after merging @Maarten-vd-Sande's #138. For now, you should be able to install from github: `pip install git+https://github.com/saketkc/pysradb`

**Comment by saketkc** [comment]
Should be fixed via the [latest release](https://github.com/saketkc/pysradb/releases/tag/v1.1.0)
