### ISSUE TITLE
[BUG] ENA search cannot handle dashes in the strategy argument

### ISSUE THREAD

**Issue by siebrenf** [saketkc/pysradb#142]
**Describe the bug**
when using `pysradb search -d ena` with the `--strategty` flag, a value containing a dash fails to produce a result.
```
--strategy must be one of the following: 
AMPLICON, ATAC-seq, Bisulfite-Seq, CLONE, CLONEEND, CTS, ChIA-PET, ChIP-Seq, 
DNase-Hypersensitivity, EST, FAIRE-seq, FINISHING, FL-cDNA, Hi-C, MBD-Seq, MNase-Seq,
MRE-Seq, MeDIP-Seq, OTHER, POOLCLONE, RAD-Seq, RIP-Seq, RNA-Seq, SELEX, 
Synthetic-Long-Read, Targeted-Capture, Tethered Chromatin Conformation Capture, 
Tn-Seq, VALIDATION, WCS, WGA, WGS, WXS, miRNA-Seq, ncRNA-Seq, ssRNA-seq, GBS
```

**To Reproduce**
```
# these work
pysradb search -d sra -m 1 --strategy RNA-seq
pysradb search -d geo -m 1 --strategy ATAC-seq
pysradb search -d ena -m 1 --strategy WGS

# these don't work
pysradb search -d ena -m 1 --strategy RNA-seq
pysradb search -d ena -m 1 --strategy ChIP-seq
pysradb search -d ena -m 1 --strategy ATAC-seq
```

**Desktop (please complete the following information):**
 - OS: Linux (5.10.16.3-microsoft-standard-WSL2)
 - Python version: 3.9.7
 - pysradb version: 1.0.1 (conda install)

**Additional context**
My guess would be its related to your [strategy matcher](https://github.com/saketkc/pysradb/blob/b91fd35e092decbc8a3f0eef2810df181812e4e9/pysradb/search.py#L394).

**Comment by saketkc** [comment]
@bscrow fixed this in #144, let us know if you encounter any issues.
