### ISSUE TITLE
[BUG] month & day swapped for publication_date?

### ISSUE THREAD

**Issue by gfudenberg** [saketkc/pysradb#145]
Thanks for the great tool!

I wonder if the month & date are swapped for the `publication_date` argument in `SraSearch`, since I find fewer entries with a date range from '01-01-2021:01-02-2021' vs '01-01-2021:02-01-2021'.

![image](https://user-images.githubusercontent.com/19657573/140439289-287e8b21-c10f-4342-a216-816a4c6af3bf.png)

Note the function nevertheless throws an error for e.g. 29-01-2021

In [2]: pysradb.__version__
Out[2]: '1.0.1'

**Comment by saketkc** [comment]
Thanks! 

The input format is 'dd-mm-yyyy' which then gets converted to 'yyyy/mm/dd'. Internally, the logic looks [correct](https://github.com/saketkc/pysradb/blob/494c5acf728a0c65883a5255a1c90f3af4299876/pysradb/search.py#L1319), but the results indeed look incorrect. Any clues @bscrow?

**Comment by bscrow** [comment]
Thank you @gfudenberg for the bug report! You are right that the month and date fields have been swapped. On the SRA server, date format in the form of 02/01/2021 is interpreted as mm/dd/yyyy instead of dd/mm/yyyy, which I missed. 
This should be resolved in #146.

**Comment by saketkc** [comment]
Thanks @bscrow for the PR!

@gfudenberg, you should be able to clone from the master branch to test the fix, I will make a release in the coming weeks.
