### ISSUE TITLE
Some problem with errors in `pysradb metadata`

### ISSUE THREAD

**Issue by jbloom** [saketkc/pysradb#148]
Using `pysradb` version 1.1.0, the following command run in a Python interpreter session kills the entire session rather than raising an exception:

    >>> import pysradb
    >>> db = pysradb.sraweb.SRAweb()
    >>> accession = 'SRR13441704'
    >>> df = db.sra_metadata(accession, detailed=True)
    No results found for SRR13441704

**Comment by saketkc** [comment]
Thanks, it is indeed not what I think it should be doing. This should be addressed by #149 and is now in pysradb 1.2.0.
