### ISSUE TITLE
`pysradb metadata --detailed` gives `KeyError` for some accessions

### ISSUE THREAD

**Issue by jbloom** [saketkc/pysradb#151]
Running this command:
```
pysradb metadata --detailed SRR12943697
```

Gives this error:
```
KeyError: 'retry-after'
```

**Comment by saketkc** [comment]
With release [1.3.0](https://github.com/saketkc/pysradb/releases/tag/v1.3.0), this results in an error because for some reason it is not possible to fetch the metadata for this record.
