### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cyto-matan** [saketkc/pysradb#153]
**Describe the bug**
gsm-to-srp is not working

**To Reproduce**
pysradb gsm-to-srp GSM2177186

**Desktop (please complete the following information):**
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
pysradb 1.3.0

**Comment by saketkc** [comment]
Can you try this with the main branch? I do not see any error (could have be an intermittent issue at NCBI end):

```bash
$ pysradb gsm-to-srp GSM2177186
experiment_alias        study_accession
GSE81903 SRP075720

```
