### ISSUE TITLE
organism name is not present in the metadata fetched through flags

### ISSUE THREAD

**Issue by deepthi888** [saketkc/pysradb#16]
Hi @saketkc,
could you please provide me information on how to fetch the name of the organism by giving project id and also how to get the count of runs and experiments of each project
I tried with this "pysradb metadata SRP063732 --desc --expand --detailed" but it fetched all the attributes information except name of the organism.

Thanks in advance

**Comment by saketkc** [comment]
Thanks @deepthi888. The support for this had been long pending.
I just pushed https://github.com/saketkc/pysradb/commit/687bb9dd12052525177767a7264a0fafecaaa57c that should produce another column `organism_name`. You can install the latest version of `pysradb` using:

`pip install git+https://github.com/saketkc/pysradb`. 

Let me know if you run into any issues.
Thanks for using `pysradb`.

**Comment by deepthi888** [comment]
Hi @saketkc,
Thanks for your response regarding fetching the organism name.

could you please provide me information  how to get the count of runs , projects, experiments and samples by giving input as organism name.

Thanks in advance.


Thanks in advance

**Comment by saketkc** [comment]
Hi @deepthi888, Unfortunately, species-wide querying is currently not possible.

**Comment by deepthi888** [comment]
Okay @saketkc , but do you have any other information on how to reach that species-wide querying in jupyter notebook. Could you please let me know

thanks.

**Comment by saketkc** [comment]
Hi @deepthi888, you can give a try to omicidx by Dr. Sean Davis: https://github.com/omicidx/omicidx
