### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by BiomedicLJZ** [saketkc/pysradb#160]
**Describe the bug**
`UnboundLocalError                         Traceback (most recent call last)
Input In [7], in <cell line: 3>()
      1 from pysradb import SRAweb
      2 db = SRAweb()
----> 3 df = db.sra_metadata('SRP098789')
      4 df.head()

File ~\PycharmProjects\Tools\venv\lib\site-packages\pysradb\sraweb.py:516, in SRAweb.sra_metadata(self, srp, sample_attribute, detailed, expand_sample_attributes, output_read_lengths, **kwargs)
    514 experiment_record["sample_title"] = exp_sample_name
    515 experiment_record["instrument"] = exp_instrument
--> 516 experiment_record["instrument_model"] = exp_platform_model
    517 experiment_record["instrument_model_desc"] = exp_platform_desc
    518 experiment_record["total_spots"] = exp_total_spots

`
**To Reproduce**
from pysradb import SRAweb
db = SRAweb()
df = db.sra_metadata('any data')
df.

**Desktop (please complete the following information):**
 - OS: [Windows11]
 - Python version [e.g. 3.10]
 - Platform [Pycharm]

**Additional context**
I just used this oackage a week ago with this exact structure and worked fine
![imagen_2022-05-24_222235489](https://user-images.githubusercontent.com/99223876/170172995-58f264d3-5140-4d55-8adb-e30a0ac6221a.png)

**Comment by BiomedicLJZ** [comment]
Also important to Report that the python env ist completely clean and that the code works in Google colab but i need it to be able to run in local

**Comment by saketkc** [comment]
Thanks, we should have caught this (seems to be coming from a change at the NCBI end though). Can you try pulling from the master branch and retry?

```bash
pip install git+https:://github.com/saketkc/pysradb
```

**Comment by jbmorlot** [comment]
Works for me, thanks!

**Comment by saketkc** [comment]
Thanks. This should now be fixed in [v.1.4](https://github.com/saketkc/pysradb/releases/tag/v1.4.0).
