### ISSUE TITLE
[BUG] KeyError: '@url'

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [saketkc/pysradb#161]
executing

```
import pysradb

sample = "DRR138929"

db_sra = pysradb.SRAweb()
db_sra.sra_metadata([sample], detailed=True)
```

leads to

```
Traceback (most recent call last):
  File "/home/sande/Desktop/seq2science/pysradb_script.py", line 6, in <module>
    db_sra.sra_metadata([sample], detailed=True)
  File "/home/sande/anaconda3/envs/pysradb/lib/python3.9/site-packages/pysradb/sraweb.py", line 581, in sra_metadata
    detailed_record["sra_url"] = sra_files["@url"]
KeyError: '@url'
```

A couple of weeks ago this worked fine for this sample. Not sure if related but it seems like the sample cannot be downloaded on AWS anymore, https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=DRR138929. Other samples from this project don't have this problem.. Idk if the data is being migrated or something?

**Comment by saketkc** [comment]
This should be fixed in [v1.4](https://github.com/saketkc/pysradb/releases/tag/v1.4.0) - NCBI is moving everything to the cloud (GCP/AWS) so some SRA cloud links are no longer available.
