### ISSUE TITLE
Is piping possible in pysradb

### ISSUE THREAD

**Issue by deepthi888** [saketkc/pysradb#17]
Can i give result of one query as input to other query and get the result using two queries in a single query?
or
Can i concatenate or merge two queries as a single query and get the output?

**Comment by saketkc** [comment]
Hi @deepthi888, piping for queries is currently not supported. At this point the search only supports string search, so concatenating queries via "AND" might not work. I will update it here once support for such operations is available. 

Sorry for not being helpful at the moment.
