### ISSUE TITLE
Unable to parse xml response. Received: OrderedDict([('EXPERIMENT_PACKAGE_SET', OrderedDict([('Error', 'Internal Server Error (db)')]))])

### ISSUE THREAD

**Issue by NayanVS** [saketkc/pysradb#173]
>conda activate pysradb
>pysradb download -p PRJNA634994
Error: Unable to parse xml response. Received: OrderedDict([('EXPERIMENT_PACKAGE_SET', OrderedDict([('Error', 'Internal Server Error (db)')]))])

It worked once but then started giving errors the second time.

**Comment by Maarten-vd-Sande** [comment]
I got the same error just now as well. I guess that's a problem on the EBI ENA side? As it says `internal server error`?

**Comment by saketkc** [comment]
Thanks for reporting the bug. I think there were some changes at the xml response from NCBI. I am looking into it.

**Comment by Maarten-vd-Sande** [comment]
Seems to be resolved for me 😄

**Comment by NayanVS** [comment]
Automatically resolved.  @saketkc @Maarten-vd-Sande Thanks a lot for your attention.
