### ISSUE TITLE
[ENH] MD5 value is not

### ISSUE THREAD

**Issue by sheep-liu** [saketkc/pysradb#179]
**Is your feature request related to a problem? Please describe.**
I am concerned that the MD5 value is missing, and I am unsure if my downloaded file is completely identical to the official data.

**Describe the solution you'd like**
I am looking forward to obtaining the MD5 value of the data downloaded from `ebi.ac.uk/vol1/fastq` to ensure that my download is correct.

**Comment by saketkc** [comment]
This is now partially addressed by including `public_md5` column in the detailed metadata output following changes in the develop branch.
