### ISSUE TITLE
Re-initiate testing for individual sub-commands of the SRAweb module

### ISSUE THREAD

**Issue by saketkc** [saketkc/pysradb#19]
The initial versions of `pysradb` relied on `SRAmetadb.sqlite` for doing the operations. The test [suite](https://github.com/saketkc/pysradb/tree/master/tests) currently is catered to that mode and has not been updated to reflect [SRAweb](https://github.com/saketkc/pysradb/blob/master/pysradb/sraweb.py).

SRAweb is going to be the only supported mode in the future as we want to do away with the dependence on SRAmetadb. This will require a new suite of tests to be written based on the existing tests (since the sub-commands are exactly the same).

**Comment by dibyaaaaax** [comment]
Hi, I would like to take up this issue but I am facing a problem.
How do I write a command to make sure SRAweb is used instead of SRAmetadb? All the command I have tried initiates the download process for SRAmetadb.sqlite.gz.

**Comment by saketkc** [comment]
Hi @dibyaaaaax, thanks for your interest! I just added a template version for testing `SRAweb` mode here: https://github.com/saketkc/pysradb/blob/master/tests/test_sraweb.py

The idea would be to test each and every function that is in `sraweb.py`. Ideally, each function should be tested on different set of SRP IDs. I have attached a list of SRPs in a file here. In order to verify if the total number of records for each SRP are correct, you will need to manually verify it using the web interface. 

# Example:
SRP: SRP016501
Online version of metadata (URL): https://www.ncbi.nlm.nih.gov/Traces/study1/?acc=SRP016501 

1.Basic check:
Verify that the total number of records is 134 as shown under the "Runs" column.

2.Advanced check:
Check if the `tissue` column in the online version is the same as in the `SRAweb` version when using `sraweb_connection.sra_metadata("SRP016501", detailed=True)`. One easy way to do this is to download the "Runinfo table" from SRA (using the `URL` above, also attached here) and check if SRAweb's output captures all the columns in the Runinfo table or not (even if the exact column name is not the same).

Please let me know if you have any questions. 
[SRP_IDs.txt](https://github.com/saketkc/pysradb/files/4242436/SRP_IDs.txt)
[SraRunTable.txt](https://github.com/saketkc/pysradb/files/4242439/SraRunTable.1.txt)

**Comment by saketkc** [comment]
Should be fixed by https://github.com/saketkc/pysradb/pull/43
