### ISSUE TITLE
Db is overwritten if run without --db command

### ISSUE THREAD

**Issue by raivivek** [saketkc/pysradb#2]
* pysradb version: pysradb, version 0.6.0
* Python version: 3.6.5
* Operating System: Linux

### Description

Running a command without specifying `--db` overwrote the already downloaded databases in the same directory.

### What I Did

```
pysradb srp-to-srx SRP067701
```

Running this twice should not download the database again

Let me know if I missed something.

Thanks for the great package, Saket!

**Comment by saketkc** [comment]
That's right Vivek. I fixed this in master: https://github.com/saketkc/pysradb/commit/02e9baf40a29e527e08802e0f65a35ebaa6aa0c6#diff-4e3fb9d066843c9540e3cff52b9ad00cR35

It's not on pypi yet. I plan to make a release sometime next week. Can you try it from the master?

**Comment by raivivek** [comment]
Thanks Saket! It works.

**Comment by saketkc** [comment]
Thank you for trying it out and really sorry for that weird bug! It should have never been like that.
