### ISSUE TITLE
[BUG] Metadata download not only for the provided accession number

### ISSUE THREAD

**Issue by cpavloud** [saketkc/pysradb#203]
Hello,

I just installed pysradb (version: 2.2.0) using conda on a Mac (Apple M2 Pro chip, Sonoma 14.0 (23A344)). 

I am running the command 
`pysradb metadata PRJEB24595 –desc –expand > PRJEB24595_pysradb_metadata.tsv `
but the output file has 14015 lines, instead of 8 (that it should have in this particular case)

I thought it was a bug having to do with the ENA project accession number so I tried this command 
`pysradb metadata SRA009436 –desc –expand > SRA009436_pysradb_metadata.tsv`
but again the output has 14039 lines, instead of 32 that it should have. 
My 32 wanted lines are there, but I thought the output was supposed to include only those...

**Comment by saketkc** [comment]
Both these commands work for me. Can you point me to the (incorrect) documentation on where you found `--desc --expand` being used?

```bash
 $ pysradb metadata PRJEB24595 --detailed --saveto PRJEB24595.tsv
 $ cat PRJEB24595.tsv| wc -l
       9
 $ pysradb metadata SRA009436 --detailed --saveto SRA009436.tsv
 $ cat SRA009436.tsv  | wc -l
      33
```

**Comment by cpavloud** [comment]
Well, I found it in the [original publication](https://f1000research.com/articles/8-532/v1), where it is mentioned that 

_We require detailed metadata associated with each sample to perform any downstream analysis. For example, the assays used for different samples and the corresponding treatment conditions. This can be done by supplying the ‘–desc’ flag_
`$ pysradb metadata SRP010679 –desc | head -5
`

_This can be further expanded to reveal the data in ‘sample_attribute’ column into separate columns via ‘–expand’ flag. This is most useful for samples that have associated treatment or cell type metadata available._
`$ pysradb metadata SRP010679 –desc –expand`

**Comment by saketkc** [comment]
Thanks! The publication is now out of date with version 2.0. Docs are available here:https://saket-choudhary.me/pysradb/
