### ISSUE TITLE
01.SRAdb-demo.ipynb's output is different from yours.

### ISSUE THREAD

**Issue by knagakura** [saketkc/pysradb#21]
* pysradb version:0.10.2
* Python version:3.6.5
* Operating System: macOS Mojave 10.14.5

### Description

I want to reproduct your .ipynb file, pysradb/notebooks/01.SRAdb-demo.
And I run that file in my local environment.
But the output is different.

I cannot understand this problem.
If you know have some solution or idea, please tell me.

Thank you for your attension.

### What I Did

```
df = db.sra_metadata('SRP017942')
df
```
![Screen Shot 2020-02-14 at 14 51 15](https://user-images.githubusercontent.com/40589218/74505077-7f8e8c00-4f39-11ea-97ce-e6c811b2b0e0.png)

**Comment by saketkc** [comment]
Hello @knagakura, thanks for your bug report. The notebooks were outdated. I have now updated them to reflect the new web-based API. The `SRAmetadb.sqlite` based API will be retired very soon as it seems to be missing certain datasets randomly. 

You will find the updated notebooks here: https://github.com/saketkc/pysradb/tree/master/notebooks

Please let me know if you have any other questions. Thanks!

**Comment by knagakura** [comment]
Thank you!!!! I can get the same information!
