### ISSUE TITLE
[BUG] Metadata download only for a few run accessions, not for all the run accessions of the study

### ISSUE THREAD

**Issue by cpavloud** [saketkc/pysradb#212]
Hello, 

I am trying to run pysradb to retrieve the metadata for the study [PRJEB55296](https://www.ebi.ac.uk/ena/browser/view/PRJEB55296). As you can see, the study has 670 run accessions. 

However, when I run the command 
`pysradb metadata PRJEB55296  --detailed --saveto output_SNMMP.txt`

it only downloads the metadata  for 7 of the accessions 
[output_SNMMP.txt](https://github.com/saketkc/pysradb/files/14311567/output_SNMMP.txt)

I have used the same command before for other studies and it worked just fine. 

Do you have any idea why is this happening?

**Desktop:**
 - OS: 14.2.1 (23C71)
 - conda version 23.7.4
 - conda-build version 3.26.1
 - python version 3.11.6.final.0

**Comment by saketkc** [comment]
In this case it is just mimicking what you see on the NCIB's SRA search page: https://www.ncbi.nlm.nih.gov/sra/?term=PRJEB55296. Not sure why SRA is not synced up with ENA

**Comment by cpavloud** [comment]
Oh that's unfortunate... I wonder why they are not synced... 
I e-mailed NCBI's helpdesk. I hope they will reply!

**Comment by cpavloud** [comment]
Just to comment, NCBI corrected the study entry and now it has all the 670 accessions!

**Comment by saketkc** [comment]
Awsome, thanks for the update! And please feel free to reopen if you notice any other issues with pysradb
