### ISSUE TITLE
Support search on SRAweb mode

### ISSUE THREAD

**Issue by saketkc** [saketkc/pysradb#22]
Floated as a GSoC 2020 project: https://www.open-bio.org/events/gsoc/gsoc-project-ideas/#pysradb

**Comment by dark00infinity** [comment]
Hi, my name is Deepak singh. I am second year student pursuing B.E. In ECE from U.I.E.T panjab university. I want to participate in gsoc with this project. 
1. I am well versed with python but i am new to pysradb module, is their any channel where i can ask doubts about it.
2. Where to send the proposals for review and suggestions

**Comment by saketkc** [comment]
Hi @dark00infinity, thanks for your interest in pysradb! 

> I am well versed with python but i am new to pysradb module, is their any channel where i can ask doubts about it.

We have a google group : https://groups.google.com/forum/#!forum/pysradb. Feel free to ask your questions there. Doubts is a stronger word, I guess you meant questions :-)

> Where to send the proposals for review and suggestions

You are welcome to send it to me or @amalthomas111. Also feel free to email us any questions that you have.

**Comment by saketkc** [comment]
WIP https://github.com/saketkc/pysradb/pull/43
