### ISSUE TITLE
Python API doc examples seem to use sra_metadata with detailed=True

### ISSUE THREAD

**Issue by victorlin** [saketkc/pysradb#39]
* pysradb version: [master](https://github.com/saketkc/pysradb/tree/6ede06)
* Python version: 3.7.4
* Operating System: macOS 10.13.6

### Description

All the outputs and commands in the [Python API documentation](https://saket-choudhary.me/pysradb/python-api-usage.html) seem to assume `sra_metadata()` is called with `detailed=True`, though it is not specified and the default value is False.

Notably, this breaks [example 4](https://saket-choudhary.me/pysradb/python-api-usage.html#use-case-4-getting-cell-type-treatment-information-from-sample-attributes) where `expand_sample_attribute_columns()` assumes presence of the `sample_attribute` column. Running this snippet yields an ambiguous `KeyError` rather than the intended output.

```py
from pysradb.filter_attrs import expand_sample_attribute_columns
df = db.sra_metadata('SRP017942')
expand_sample_attribute_columns(df).head()
```

**Comment by saketkc** [comment]
Thanks for the bug report @victorlin!

We are trying to move away from use of `SRAmetadb.sqlite`.
That said, the API did change in between and hence there is a discordance between the docs and the API.

I would encourage you to try the `SRAweb` API which is more generic and always up-to-date. Here is an example for the metadata API: https://colab.research.google.com/drive/1BxsLlD_jJGAu5n377DK5RuZJrRiY-gUz

You can find other examples in the notebooks directory. We will soon migrating all the docs to the `SRAweb` API once the search functionality is up and working. See #22.

**Comment by saketkc** [comment]
Fixed with latest docs update.
