### ISSUE TITLE
Regarding Non-available dataset in the package

### ISSUE THREAD

**Issue by himanshusingh2018** [saketkc/pysradb#4]
* pysradb version: 0.9.0
* Python version: 3.7
* Operating System: Ubuntu Linux

### Description
I found few datasets are not available in the provided SRAmetadb.sqlite file. For example: GSE80994, GSE80993, GSE80992 etc. How can I get all the datasets from this tool? If the dataset is not available, how can I add it into the package?

### What I Did

```
pysradb gse-to-gsm --db SRAmetadb.sqlite --desc --expand GSE80990
/home/singh/miniconda3/envs/dev/lib/python3.7/site-packages/pysradb/basedb.py:108: RuntimeWarning: Found no matching results for query.
  warnings.warn("Found no matching results for query.", RuntimeWarning)
```

**Comment by saketkc** [comment]
It looks like these GSEs are not yet available in `SRAmetadb.sqlite`. Unfortunately, I do not have a timeline for when these projects will be accessible through `pysradb` as it depends on updates upstream.

**Comment by saketkc** [comment]
Hi @himanshusingh2018, I am going to close this since your query is limited by `SRAmetadb.sqlite` itself. Please feel free to re-open if you face any difficulty with `pysradb`. Thanks for using `pysradb`.

**Comment by himanshusingh2018** [comment]
Hi @saketkc. Thank you for helping me in the regard. However, I have just one query that can we add any GSE dataset in SRAmetadb.sqlite manually? 
Thanks

**Comment by saketkc** [comment]
In theory, yes. But it will require you to update the records across [tables](https://render.githubusercontent.com/view/ipynb?commit=04284f22481c810152483ecc30055d17ed8561ec&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f73616b65746b632f707973726164622f303432383466323234383163383130313532343833656363333030353564313765643835363165632f6e6f7465626f6f6b732f30312e53524164622d64656d6f2e6970796e62&nwo=saketkc%2Fpysradb&path=notebooks%2F01.SRAdb-demo.ipynb&repository_id=159590788&repository_type=Repository#Describe-columns-in-a-table). 

Scripts to generate SRAmetadb.sqlite are not public and hence manually adding datasets is not possible, practically.

**Comment by himanshusingh2018** [comment]
Thank you for your response. Can you suggest me something, where I can get all the datasets available on SRA db? Like we fetch in pysradb...
Thanks

**Comment by saketkc** [comment]
You can try SRAdbv2: https://github.com/seandavi/SRAdbV2

**Comment by himanshusingh2018** [comment]
Thank you for your suggestion.

**Comment by saketkc** [comment]
Yes, you can use `gsm-to-srr` subcommand for this.

**Comment by himanshusingh2018** [comment]
Thanks.

**Comment by saketkc** [comment]
Hi @himanshusingh2018 ,

With the latest version of pysradb (0.9.6) you should be able to obtain the metadata even if it is not available in the SRAmetadb.sqlite file.

```
$ pysradb  gse-to-gsm  GSE80990
study_alias experiment_alias experiment_accession
 SRP074240   GSM2946898       SRX3596655         
 SRP074240   GSM2946897       SRX3596654         
 SRP074240   GSM2946896       SRX3596653         
 SRP074240   GSM2946895       SRX3596652         
```

```
$ pysradb gsm-to-srr GSM1055806 GSM1055807
experiment_alias run_accession
 GSM1055807       SRR639051   
 GSM1055806       SRR639050   
```

Please make sure you rune
