### ISSUE TITLE
directing output in external hard drive

### ISSUE THREAD

**Issue by amitpande74** [saketkc/pysradb#42]
Hi, 
I want to redirect the download to an external hard drive since I have little space left in my hard drive.
I am trying 
(pysradb) usr@usr-X705UDR:~$ pysradb download --out-dir ./pysradb_downloads -p SRP165962 --db cd /media/usr/LaCie/db/ , but it is not working.
Kindly help.

**Comment by saketkc** [comment]
Hi @amitpande74, You should be able to set a custom directory for the downloads using `--out-dir`:

```
pysradb download -p SRP165962 --out-dir /path/to/xyz
```

Feel free to reopen if you face any issues.

**Comment by amitpande74** [comment]
Hi @saketkc 
I tried the command 
pysradb download -p SRP165962 --out-dir , but it only downloads the empty folders.

**Comment by amitpande74** [comment]
Hi @saketkc
I tried the command
pysradb download -p SRP165962 --out-dir , but it only downloads the empty folders.

**Comment by saketkc** [comment]
Hi @amitpande74, I am unable to replicate this at my end. 
See this notebook for an example: https://colab.research.google.com/drive/141ambHwCshyMZlZjgQgci6WCEZv6Z2KO

**Comment by amitpande74** [comment]
Hi,
I think I found out the problem.
`SRP165962       SRX4896814           SRS3943426       SRR8068516    anonftp@ftp-trace.ncbi.nlm.nih.gov:/sra/sra-instant/reads/ByRun/sra/SRR/SRR806/SRR8068516/SRR8068516.sra`
Whereas in the colab notebook which you shared, this link is not being shown.
and when i checked the link ftp-trace.ncbi.nlm.nih.gov:/sra/sra-instant/ it is empty.
how to avoid this ?
Is sra-tools a requirement ? 'cause I dont have this installed.

**Comment by saketkc** [comment]
The file is here:  https://sra-download.ncbi.nlm.nih.gov/traces/sra67/SRR/007879/SRR8068516  (See last line)
and pysradb does download it. I aborted the complete download since there is not enough space on colab to do so.

**Comment by saketkc** [comment]
Are you using `SRAmetadb.sqlite`? Please make sure you do not have it in your current working directory. We are moving away from `SRAmetadb`. The above commands are for `SRAweb` mode  which does not require `SRAmetadb.sqlite`.
