### ISSUE TITLE
Pysradb metadata does not work for some project accession numbers

### ISSUE THREAD

**Issue by bscrow** [saketkc/pysradb#45]
`pysradb metadata --saveto test1.tsv --detailed SRP098789` and `pysradb metadata ERP113893` works well. 
However, `pysradb metadata --detailed ERP113893` or `pysradb metadata --saveto test1.tsv --detailed ERP113893` produces the following IndexError:

![image](https://user-images.githubusercontent.com/38070760/85672699-be0d3200-b6f5-11ea-8628-f0da44665541.png)

I am able to replicate this issue on pysradb-0.10.4 (from pypi) and pysradb-0.10.5-dev0 (from github pysradb master), on both windows 10 and Ubuntu 18.04 OS.

**Comment by leipzig** [comment]
SRP141397 doesn't work in any of these scenarios

```
pysradb metadata --db ./SRAmetadb.sqlite SRP141397 --detailed --expand --saveto metadata/SRP141397.metadata
Found no matching results for query.
```

**Comment by saketkc** [comment]
Thanks @bscrow. This is fixed in https://github.com/saketkc/pysradb/commit/7892a30a219c00ecda0034d21924ee86d169c7db.

Example notebook: https://colab.research.google.com/drive/1vkhbI_4z7zF-yJATRUGtqlQXr0KmYqD5?usp=sharing
