### ISSUE TITLE
Empty results error while searching

### ISSUE THREAD

**Issue by sebboegel** [saketkc/pysradb#49]
Mac OS Cataline 10.15.5
python 2.7
pysradb 0.7.0

SRAmetadb.sqlite downloaded and extracted

Sebastians-Air:pysradb sebastian$ pysradb search '"single-cell rna-seq" retina'
/Users/sebastian/Library/Python/2.7/lib/python/site-packages/pysradb/basedb.py:108: RuntimeWarning: Found no matching results for query.
  warnings.warn("Found no matching results for query.", RuntimeWarning)
/Users/sebastian/Library/Python/2.7/lib/python/site-packages/pysradb/sradb.py:243: UserWarning: Empty results
  warnings.warn("Empty results", UserWarning)

**Comment by saketkc** [comment]
We are moving away from the `SRAmetadb.sqlite` approach. If you are interested please feel free to try https://github.com/saketkc/pysradb/pull/43. An example notebook is here: https://colab.research.google.com/drive/1Rq0tpT3UwtpZywIgicWaFgnonprKMg93?usp=sharing

Sorry about the inconvenience.
