### ISSUE TITLE
discrepancies between websearch and pysradb

### ISSUE THREAD

**Issue by sebboegel** [saketkc/pysradb#50]
Mac OS Cataline 10.15.5
python 3.8
pysradb 0.10.5-dev0

https://www.ncbi.nlm.nih.gov/sra/?term=(rheumatoid+arthritis)+AND+%22Homo+sapiens%22%5Borgn%3A__txid9606%5D yileds 6514 entries

pysradb search -q "rheumatoid arthritis" -m 9000 results in only 287 entries.

What did i wrong?

**Comment by saketkc** [comment]
Thanks for trying out our experimental feature @sebboegel, appreciate your efforts! I will page in @bscrow who has been working on this. 

@bscrow  do you know the source of discrepancy?

**Comment by bscrow** [comment]
Yep it is a bug. I will push a fix in the next update.

Thanks for the bug report!

**Comment by sebboegel** [comment]
Thank you very much for the fast response and thanks for the tool. It is really valuable. One thing i love is that the output table contains the pmid, which i havent seen in the metadata txt file one can download from SRArunselector.
