### ISSUE TITLE
[BUG] experiment_alias has _1 appended

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [saketkc/pysradb#55]
**Describe the bug**```
Not sure if its a bug on the GEO/SRA side, but for GSM sample `GSM1020644` the experiment_alias has `_1` appended in its experiment_alias. I have not seen `_1` anywhere on the website.

```
import pysradb
print(pysradb.__version__)
print(SRAweb().sra_metadata("GSM1020644", detailed=True).experiment_alias.values)
```
```
0.11.0
['GSM1020644_1']
```

**Comment by saketkc** [comment]
Thanks for the question @Maarten-vd-Sande. Your observation is correct and I understand that this is a bit unintuitive. However,
this metadata is as is received from SRA/GEO. One reason the `_1` or `_2` exists in GSM ids is to reflect the different technical runs for an experiment.

I hope the explanation helps. I will go ahead and close this, but please feel free to reopen if you notice any other issues related to this.
