### ISSUE TITLE
Sample exists on GEO, but not on SRA

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [saketkc/pysradb#58]
### Description

I have a *strange* issue, which might not be within the scope of pysradb.

Sample GSM3832552 (actually the whole series) has been submitted to GEO but is not on the SRA. The sequencing runs however are on the SRA. Is there some magic way I can work with those?

```python
>>> import pysradb
>>> print(pysradb.__version__)
0.11.1-dev0
>>> print(pysradb.SRAweb().sra_metadata("GSM3832552", detailed=True))
No results found for GSM3832552
```

**Comment by Maarten-vd-Sande** [comment]
Current solution for me is to look up the sample first on GEOparse and use its SRX number and continue with that with pysradb. I guess that's as good as it gets in these cases right?

**Comment by saketkc** [comment]
The problem seems to be because https://www.ncbi.nlm.nih.gov/sra/?term=GSM3832552 returns empty results (because for some reason GSM3832552 was not properly propogated in the metadata records on SRA).

You can get all the metadata using `pysradb`, though it requires two calls:

```bash
$ pysradb gsm-to-srx GSM3832552
experiment_alias experiment_accession
GSM3832552       SRX5706709 
```

```bash
$ pysradb metadata SRX5706709
study_accession experiment_accession experiment_title                experiment_desc                 organism_taxid  organism_name library_strategy library_source library_selection library_layout sample_accession sample_title instrument           total_spots total_size  run_accession run_total_spots run_total_bases
SRP192924       SRX5706709           EC_038_HCCaEC ChIP-seq H3K27ac  EC_038_HCCaEC ChIP-seq H3K27ac  9606            Homo sapiens  ChIP-Seq         GENOMIC        ChIP              SINGLE         SRS4480310                    Illumina HiSeq 2500  51976162    1673205843  SRR8925655    51976162        2650784262    
```

The GSM to SRX command fetches records from GEO.

**Comment by Maarten-vd-Sande** [comment]
Ah somehow I did not think of that :facepalm: , thanks! That saves another dependency.
