### ISSUE TITLE
[BUG] layout reported as @xmlns

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [saketkc/pysradb#64]
**Describe the bug**
Looking up the layout of sample GSM1013144 reports a layout of `@xmlns`. 

My guess would be that the xml is parsed incorrectly:
https://www.w3schools.com/tags/att_html_xmlns.asp

The SRA entry namely is single-ended:
https://www.ncbi.nlm.nih.gov/sra?term=GSM1013144

**To Reproduce**
```
import pysradb
db = pysradb.SRAweb()
db.sra_metadata("GSM1013144")
```

**Comment by saketkc** [comment]
fixed via #65
