### ISSUE TITLE
[ENH] Platform/base space in metadata

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [saketkc/pysradb#75]
**Is your feature request related to a problem? Please describe.**
I run into the problem with seq2science that we assume that all samples are illumina sequenced / base space. Someone tried to run it with ABI solid and this resulted in some unexpected behaviour (empty alignment, but pipeline still runs fully). I want to add a check if the sample platform / fastq format is supported, but I am not sure if I can retrieve this data with pysradb:

```python
import pysradb

db_sra = pysradb.SRAweb()
metadata = db_sra.sra_metadata(["SRR1649197"], detailed=True)
print(metadata.columns)
```
```
Index(['run_accession', 'study_accession', 'experiment_accession',
       'experiment_title', 'experiment_desc', 'organism_taxid ',
       'organism_name', 'library_strategy', 'library_source',
       'library_selection', 'library_layout', 'sample_accession',
       'sample_title', 'instrument', 'total_spots', 'total_size',
       'run_total_spots', 'run_total_bases', 'run_alias', 'sra_url',
       'experiment_alias', 'source_name', 'cell type', 'ena_fastq_http',
       'ena_fastq_http_1', 'ena_fastq_http_2', 'ena_fastq_ftp',
       'ena_fastq_ftp_1', 'ena_fastq_ftp_2'],
      dtype='object')
```

See this sample for https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1649197

The instrument is `AB 5500 Genetic Analyzer`, which is something I could use, but I expect to run into the same problem again when people use a different machine but still ABI solid (assuming there are multiple machines).

**Describe the solution you'd like**
The platform reported, or even better, the base format reported (e.g. base space vs color space).

**Comment by saketkc** [comment]
Can definitely be supported as @bscrow fetches this for doing search on SRA. I'll try to get to this over the weekend.

**Comment by saketkc** [comment]
Sorry for the delay. https://github.com/saketkc/pysradb/pull/94 should fix it with `instrument_model_desc`.

**Comment by Maarten-vd-Sande** [comment]
Awesome! Happy holidays🎄⛄
