### ISSUE TITLE
SRS to GSM support

### ISSUE THREAD

**Issue by spadavec** [saketkc/pysradb#9]
* pysradb version: 0.9.0
* Python version: 3.6
* Operating System: Linux

### Description

Can you include support for SRS to GSM conversions? I'm currently relying on the SRA_Accessions table for such conversions, and its not extremely well populated.

**Comment by saketkc** [comment]
Sure, coming up soon!

**Comment by saketkc** [comment]
Hi @spadavec,

This is now supported.

```
$ pysradb srs-to-gsm SRS718878
sample_accession sample_alias
SRS718878        GSM1521543
$ pysradb gsm-to-srs GSM1521543
sample_alias sample_accession
GSM1521543   SRS718878
```

It's not on pypi yet so please install from the master and let me know if you run into any issues.
Thanks!
