### ISSUE TITLE
[ENH] Start using pd.NA instead of "N/A"

### ISSUE THREAD

**Issue by kpj** [saketkc/pysradb#90]
**Is your feature request related to a problem? Please describe.**
When counting how much data is available, one typically looks for occurrences of `np.nan` or `pd.NA`.
At the moment, `pysradb` uses the string `N/A` instead. See e.g.:
https://github.com/saketkc/pysradb/blob/c23d4a769543d05a0f002d1b28c985da5963573f/pysradb/sraweb.py#L633

**Describe the solution you'd like**
Starting with version 1.0.0, `pandas` uses `pd.NA` to indicate [missing data](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html#experimental-na-scalar-to-denote-missing-values).

While it is currently still experimental, it might make sense to think about switching to using it.

**Comment by saketkc** [comment]
I think it's a great suggestion, I'll add it.
