### ISSUE TITLE
version 1.0?

### ISSUE THREAD

**Issue by jbloom** [saketkc/pysradb#98]
Do you plan to release version 1.0 via `PyPI` or `conda` soon? I noticed that the docs now appear to be for version 1.0, but the latest version not on GitHub is <1.0.

**Comment by saketkc** [comment]
Hi Dr. Bloom,

Yes, I should be releasing 1.0 soon in the  next couple of weeks. The documentation still requires some work. I might be doing an intermediate release before completely dropping off the `SRAmetadb.sqlite` support in 1.0.

Hope that helps. For the time being I would recommend installing from the master branch.

Thanks,
Saket

**Comment by jbloom** [comment]
Great, this seems like an awesome package. If you are able to remember to tag me when you do next release, that would be great. (Also, congrats on move to Satija lab!)

**Comment by saketkc** [comment]
Thanks a lot, Dr. Bloom! Just release `1.0` on [pypi](https://pypi.org/project/pysradb/) with updated documentation: https://saket-choudhary.me/pysradb/index.html
Let me know if you find anything amiss.

**Comment by jbloom** [comment]
This is great, thanks so much!
