### ISSUE TITLE
[ENH] Download support for gs:// links

### ISSUE THREAD

**Issue by chrlarsen** [saketkc/pysradb#99]
Is there planned support for downloading gs:// links in a future release? If not I'm more than happy to work on it.

One pitfall that I forsee is that the Google Cloud Storage python client library no longer supports 2.7 for releases after 01/01/2020.

**Comment by saketkc** [comment]
Thanks, Chris! Support for gs:// is not in the plans but very much welcome. `pysradb` is fully Python3, so it should not be a problem. I'll look forward to your PR!

**Comment by chrlarsen** [comment]
Sounds good to me!
